os: linux
dist: xenial
language: java
jdk:
  - openjdk10
addons:
  apt:
    packages:
      - ant
before_script:
   - sudo apt-get install ant-optional

script: ant junit

notifications:
    email:
        on_success: never
        on_failure: always
