language: java
script: ant junit

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ant
      - ant-optional

notifications:
    email:
        on_success: never
        on_failure: always
